### ISSUE TITLE
r132

### ISSUE THREAD

**Issue by joshuaellis** [three-types/three-ts-types#114]
### Issue Tracker

This is used to track potential issues we need to investigate surrounding the `r132` release.

- [x] MeshPhysicalMaterial: Promote ior to a material property (mrdoob/three.js#22238)
- [x] VSM Shadows: Add support for setting the number of blur samples (mrdoob/three.js#22272)
- [x] Add and/or update power() getter/setters (mrdoob/three.js#22298)
- [x] Removed webgl_materials_parallaxmap (mrdoob/three.js#22370)
- [x] Enable mat2/3/4 attribute in shader (mrdoob/three.js#16141)
- [x] MeshPhysicalMaterial.sheen -> .sheenTint (mrdoob/three.js#22381)
- [x] Removed .isBlack() method (mrdoob/three.js#22385)
- [x] MeshPhysicalMaterial: Update version for certain transmission changes. (mrdoob/three.js#22379)
- [x] Add perspective size attenuation option to LineMaterial (mrdoob/three.js#16912)
- [x] WebGLRenderer: Add support for GLTF opaque alpha_mode (mrdoob/three.js#22428)

Last checked: mrdoob/three.js@dc86b54624 (30 / 08 / 21).

**Comment by 0b5vr** [comment]
> Removed .isBlack() method (mrdoob/three.js#22385)

It seems `Color.isBlack` is added and removed within the r132. We have nothing to do I believe.

**Comment by 0b5vr** [comment]
> MeshPhysicalMaterial: Promote ior to a material property (mrdoob/three.js#22238)

`ior` is promoted to an actual member value while `reflectivity` still exists as a `get` / `set` property (i.e. the standing of `ior` and `reflectivity` has been swapped).
If we want to do something about this, we might want to change the `reflectivity` to getter / setter instead of a member?

https://github.com/three-types/three-ts-types/blob/6a5f78138c10ca144f15f4e3ea3b989c60f307d1/types/three/src/materials/MeshPhysicalMaterial.d.ts#L73-L81

**Comment by soadzoor** [comment]
@joshuaellis Are we still missing some features for r132? When can we make a new release?

**Comment by Methuselah96** [comment]
@soadzoor Yeah, the unchecked items in the descriptions are what we're still missing. Once those those are completed we can make a new release. Feel free to contribute to help it get released more quickly!

**Comment by joshuaellis** [comment]
Sorry folks, i've been incredibly busy at work and have neglected all my OSS work. Catching up now starting with this 💪🏼 r132 is in a PR in DT – https://github.com/DefinitelyTyped/DefinitelyTyped/pull/55858
