### ISSUE TITLE
r133

### ISSUE THREAD

**Issue by joshuaellis** [three-types/three-ts-types#129]
### Issue Tracker

This is used to track potential issues we need to investigate surrounding the `r133` release.

- [x] mrdoob/three.js#22457
- [x] mrdoob/three.js#22466
- [ ] mrdoob/three.js#22486
- [x] mrdoob/three.js#22404
- [ ] ~mrdoob/three.js#22488~
- [ ] mrdoob/three.js#22497
- [x] mrdoob/three.js#22460
- [x] mrdoob/three.js#22494
- [x] mrdoob/three.js#22499
- [x] mrdoob/three.js#21989
- [x] mrdoob/three.js#22513
- [ ] mrdoob/three.js#22518
- [ ] ~mrdoob/three.js#22516~
- [x] mrdoob/three.js#22533
- [x] mrdoob/three.js#22536
- [x] mrdoob/three.js#22539
- [ ] mrdoob/three.js#22538
- [x] mrdoob/three.js#22540
- [x] mrdoob/three.js#22551
- [x] mrdoob/three.js#22559
- [x] mrdoob/three.js#22560
- [x] mrdoob/three.js#22566
- [x] mrdoob/three.js#22571

Last checked: mrdoob/three.js@b1ede8160b (03 / 10 / 21).

**Comment by 0b5vr** [comment]
https://github.com/mrdoob/three.js/pull/22571 , procedural BufferGeometries like `BoxBufferGeometry` might want to change the return type of `.clone()` .

**Comment by 0b5vr** [comment]
https://github.com/mrdoob/three.js/pull/22603 , looks so many stuff related to NodeMaterial has been introduced.

**Comment by 0b5vr** [comment]
https://github.com/mrdoob/three.js/pull/22474 , several signature changes for `WebGLNodeBuilder`

(discraimer: my comments are not exhaustive)

**Comment by 0b5vr** [comment]
https://github.com/mrdoob/three.js/pull/22548 , vectors are now iterable

**Comment by joshuaellis** [comment]
> mrdoob/three.js#22548 , vectors are now iterable=

@0b5vr & @Methuselah96 Do we need to type this? If so how should it be done? 🤔

**Comment by joshuaellis** [comment]
I've released there's two versions of `node` "stuff". I've asked in Discord if there's a difference between `three/examples/jsm/nodes` and `three/examples/jsm/renderers/nodes` because that's confusing for me and we currently don't even cover the later.

Whilst we're waiting on that, I've added everything else and will submit a PR to DT now.

**Comment by Methuselah96** [comment]
Yeah, we should probably type it or just wait for a contributor to add it. Don't have much time to look into it myself at the moment. Maybe create a separate "help wanted" issue?

**Comment by joshuaellis** [comment]
I think we should wait, it's pretty confusing what needs doing when they're named the same in the repo 🤪. I'll make a seperate issue and tag `help wanted`
