### ISSUE TITLE
r134

### ISSUE THREAD

**Issue by joshuaellis** [three-types/three-ts-types#139]
### Issue Tracker

This is used to track potential issues we need to investigate surrounding the `r134` release.

- [x] mrdoob/three.js#22635
- [x] mrdoob/three.js#22642
- [x] mrdoob/three.js#22643
- [x] mrdoob/three.js#22654
- [x] mrdoob/three.js#22678
- [x] mrdoob/three.js#22698
- [x] mrdoob/three.js#22707
- [x] mrdoob/three.js#22719
- [x] mrdoob/three.js#22737
- [x] mrdoob/three.js#22721
- [x] mrdoob/three.js#22687
- [x] mrdoob/three.js#22748

Last checked: mrdoob/three.js@00a692864f (02 / 11 / 21).

**Comment by xawill** [comment]
Any progress on this release ?

**Comment by robertlong** [comment]
Here's the types for `LoaderUtils.resolveURL()`
https://github.com/three-types/three-ts-types/pull/148

**Comment by joshuaellis** [comment]
I've made a PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/57022
