### ISSUE TITLE
r135

### ISSUE THREAD

**Issue by joshuaellis** [three-types/three-ts-types#147]
### Issue Tracker

This is used to track potential issues we need to investigate surrounding the `r134` release.

- [x] mrdoob/three.js#22754
- [x] mrdoob/three.js#22752
- [x] mrdoob/three.js#22755
- [x] ~mrdoob/three.js#22778~
- [x] ~mrdoob/three.js#22759~
- [x] ~mrdoob/three.js#22813~
- [x] mrdoob/three.js#22815
- [x] ~mrdoob/three.js#22790~
- [x] mrdoob/three.js#22825
- [x] mrdoob/three.js#22851
- [x] mrdoob/three.js#22857

Last checked: mrdoob/three.js@6a67d00f86 (24 / 11 / 21).

**Comment by joshuaellis** [comment]
Will be resolved by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/57551
