### ISSUE TITLE
r136

### ISSUE THREAD

**Issue by joshuaellis** [three-types/three-ts-types#152]
### Issue Tracker

This is used to track potential issues we need to investigate surrounding the `r136` release.

- [x] mrdoob/three.js#22916
- [x] mrdoob/three.js#22932
- [x] mrdoob/three.js#22972
- [x] ~mrdoob/three.js#23028~
- [x] mrdoob/three.js#23049
- [x] mrdoob/three.js@e44441a558
- [x] mrdoob/three.js#23060
- [x] mrdoob/three.js#23080
- [x] mrdoob/three.js#23082

Last checked: mrdoob/three.js@1a241ef100 (03 / 01 / 22).

**Comment by joshuaellis** [comment]
will be resolved by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/57947
