### ISSUE TITLE
r137

### ISSUE THREAD

**Issue by joshuaellis** [three-types/three-ts-types#154]
### Issue Tracker

This is used to track potential issues we need to investigate surrounding the `r137` release.

- [x] mrdoob/three.js#23124
- [x] mrdoob/three.js#23129
- [x] mrdoob/three.js#23143
- [x] mrdoob/three.js@94ba66cfed
- [x] mrdoob/three.js#23152
- [x] ~mrdoob/three.js#23158~
- [x] mrdoob/three.js#23157
- [x] mrdoob/three.js#23177
- [x] mrdoob/three.js#23223
- [x] mrdoob/three.js#23173
- [x] mrdoob/three.js#23228
- [x] mrdoob/three.js#23231
- [x] mrdoob/three.js#23230
- [x] mrdoob/three.js#23252
- [x] mrdoob/three.js#23232
- [x] mrdoob/three.js#23166
- [x] mrdoob/three.js#23290
- [x] mrdoob/three.js#20024
- [x] mrdoob/three.js#23323
- [x] mrdoob/three.js#23326

Last checked: mrdoob/three.js@eda64d524b (27 / 01 / 22).

**Comment by 0b5vr** [comment]
#159 goes for mrdoob/three.js#23228

**Comment by 0b5vr** [comment]
Gonna do https://github.com/mrdoob/three.js/pull/23166 which is not on the list
