### ISSUE TITLE
r138

### ISSUE THREAD

**Issue by joshuaellis** [three-types/three-ts-types#164]
### Issue Tracker

This is used to track potential issues we need to investigate surrounding the `r138` release.

- [x] mrdoob/three.js@dfca2bd474
- [x] mrdoob/three.js@1d98f9d4d3
- [x] mrdoob/three.js#23402
- [x] mrdoob/three.js#23404
- [x] mrdoob/three.js#22846
- [x] mrdoob/three.js#23414
- [x] mrdoob/three.js#23418
- [x] mrdoob/three.js#23421
- [x] mrdoob/three.js#23443
- [x] mrdoob/three.js#22772
- [x] mrdoob/three.js#23454
- [x] mrdoob/three.js#23455
- [x] mrdoob/three.js#23494
- [x] mrdoob/three.js#23498
- [x] mrdoob/three.js#23481
- [x] mrdoob/three.js#23541

Last checked: mrdoob/three.js@925fa24d6f (01 / 03 / 22).

**Comment by 0b5vr** [comment]
https://github.com/mrdoob/three.js/milestone/51

https://github.com/mrdoob/three.js/compare/r137...r138

https://github.com/mrdoob/three.js/releases/tag/r138

**Comment by 0b5vr** [comment]
addressed the https://github.com/mrdoob/three.js/pull/23414.

https://github.com/three-types/three-ts-types/pull/179

**Comment by 0b5vr** [comment]
gonna do https://github.com/mrdoob/three.js/pull/22846 , which is going to be a moderate amount of diff.

Update: #180

**Comment by 0b5vr** [comment]
gonna do https://github.com/mrdoob/three.js/pull/23498

Update: #183

**Comment by 0b5vr** [comment]
gonna do https://github.com/mrdoob/three.js/pull/23494

Update: #184

**Comment by 0b5vr** [comment]
gonna do https://github.com/mrdoob/three.js/pull/23386

Update: #185

**Comment by 0b5vr** [comment]
gonna do https://github.com/mrdoob/three.js/pull/23420

Update: #186

**Comment by 0b5vr** [comment]
I have no knowledge about node material and have no idea what happened @ https://github.com/mrdoob/three.js/pull/23418 ......
Is there anything we should do?

Update: https://github.com/mrdoob/three.js/pull/23314 also has a lot of signature changes related to node materials

**Comment by 0b5vr** [comment]
have done the https://github.com/mrdoob/three.js/pull/22772 : #187

**Comment by 0b5vr** [comment]
gonna do https://github.com/mrdoob/three.js/pull/23444

Update: #188

**Comment by 0b5vr** [comment]
gonna do https://github.com/mrdoob/three.js/pull/23455

Update: #190

**Comment by 0b5vr** [comment]
gonna do https://github.com/mrdoob/three.js/pull/23481

Update: #191

**Comment by 0b5vr** [comment]
I think I've seen all the signature changes in r138. 50% confidence

**Comment by joshuaellis** [comment]
I've gone through and might have got more, but need to check the PRs in details. Lets aim 138 at master from now since it's the current release.

**Comment by joshuaellis** [comment]
will be resolved by [#59045](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/59045)
