### ISSUE TITLE
r139

### ISSUE THREAD

**Issue by joshuaellis** [three-types/three-ts-types#192]
### Issue Tracker

This is used to track potential issues we need to investigate surrounding the `r138` release.

- [x] mrdoob/three.js#23569
- [x] mrdoob/three.js#23586
- [x] mrdoob/three.js#23596
- [x] ~mrdoob/three.js#23624~
- [x] mrdoob/three.js#23619
- [x] mrdoob/three.js#23392
- [x] mrdoob/three.js#23682
- [x] mrdoob/three.js#23716
- [x] mrdoob/three.js#23756
- [x] mrdoob/three.js#23762

Last checked: mrdoob/three.js@1e0cdd9c63 (26 / 03 / 22).
