### ISSUE TITLE
r127

### ISSUE THREAD

**Issue by joshuaellis** [three-types/three-ts-types#32]
### Issue Tracker

This is used to track potential issues we need to investigate surrounding the `r127` release.

- [x] ~Scene.background does not support WebGLCubeRenderTarget anymore (mrdoob/three.js#21360)~ #33
- [x] TGALoader extends DataTextureLoader (and other things, check file) (mrdoob/three.js@db08acdd9c) #51
- [x] ~Material: Add alphaToCoverage (mrdoob/three.js@7fdf7b78fc)~ #36 
- [x] Animation system for PMX (mrdoob/three.js@9728bf414a) #56 
- [x] ~WebGLRenderer: Refactor framebuffer state management (mrdoob/three.js@e903c848d8)~ #45 
- [x] ~WebGLShadowMap: Ensure to use the latest reference to WebGLObjects. (mrdoob/three.js@632b2e6a6)~ #42 
- [x] Add GPU Progressive Lightmapping Example (mrdoob/three.js@71332b0e0b) #58
- [x] ~Remove AssimpLoader (mrdoob/three.js@7328f1da0c)~ #46 
- [x] ~Plane: Return null instead of undefined~ #47 
- [x] Line2: Add support for Alpha To Coverage (mrdoob/three.js@4ef312e7ff) #52 
- [x] SVGLoader: Implement custom createShapes() method (mrdoob/three.js@053b48bd96) #53 
- [x] Make `applyMatrix4` work on a `BufferGeometry` with `InterleavedBufferAttribute` (mrdoob/three.js@bfc15babad) #57 
- [x] ~Sphere: Add expandByPoint() and union() (mrdoob/three.js@95ce8f1400)~ #55 
- [x] ~WebGLRenderer: Remove morph target properties (mrdoob/three.js@b08a5f5b5d)~ #59 
- [x] SSRPass: Correct Reflector depth (mrdoob/three.js@07e58027cd) #62
- [x] IFCLoader (mrdoob/three.js@7c1f477316) #63
- [x] ~MathUtils: Added .inverseLerp() (mrdoob/three.js@2916db98f0)~ three-types/three-ts-types@df5a8b3
- [x] Add SSRrPass (mrdoob/three.js@cb9f8d0e5d) #64

Last checked: mrdoob/three.js@0e8e04305a (30 / 03 / 21).
