### ISSUE TITLE
r128

### ISSUE THREAD

**Issue by joshuaellis** [three-types/three-ts-types#66]
### Issue Tracker

This is used to track potential issues we need to investigate surrounding the `r128` release.

- [x] ~GLTFLoader: Add createNodeMesh hook (mrdoob/three.js#21458)~
- [x] ~Remove XLoader (mrdoob/three.js#21617)~
- [x] ~SSRPass: Change surfDist and infiniteThick behavior (mrdoob/three.js#21539)~
- [x] ~Examples: Refactored OimoPhysics example. (mrdoob/three.js@e35862887b)~
- [x] ~VRMLLoader: Upgrade chevrotain to latest version. (mrdoob/three.js#21694)~
- [x] ~Bring dat.gui inside vr (mrdoob/three.js#21700)~

Last checked: mrdoob/three.js@a1cffe93fe (24 / 04 / 21).
