### ISSUE TITLE
r129

### ISSUE THREAD

**Issue by joshuaellis** [three-types/three-ts-types#75]
### Issue Tracker

This is used to track potential issues we need to investigate surrounding the `r129` release.

- [x] ~LineSegments2: Fix typo in raycast (mrdoob/three.js#21760)~
- [x] ~Remove "copy" function override (mrdoob/three.js#21782)~
- [x] ~Material: Remove skinning (mrdoob/three.js#21788)~
- [x] ~MRT Support (mrdoob/three.js#16390)~
- [x] ~Fixing Oculus hands rendering broken by recent WebXR Hands API change (mrdoob/three.js#21712)~
- [ ] Potentially add nodes since it's simpler because they've moved to ES6 classes (mrdoob/three.js#21801)
- [x] ~Object3D: Add removeFromParent() (mrdoob/three.js#21826)~
- [x] ~Matrix4: generalize .makeShear() method (mrdoob/three.js#21822)~
- [x] ~Skeleton: Add computeBoneTexture(). (mrdoob/three.js#21829)~
- [x] ~Improve MeshPhysicalMaterial transmission support (mrdoob/three.js#21884)~
- [x] ~PerspectiveCamera: Moved frameCorners() to CameraUtils in examples. (mrdoob/three.js#21825)~

Last checked: mrdoob/three.js@d39d82999f (27 / 05 / 21).

**Comment by ycw** [comment]
Missing type decl ( `Pass` and `FullScreenQuad` ) in 'examples/jsm/postprocessing/EffectComposer.d.ts' 
according to https://github.com/mrdoob/three.js/blob/dev/examples/jsm/postprocessing/EffectComposer.js#L318

**Comment by joshuaellis** [comment]
hi @ycw, please make a separate and detailed bug report for us to resolve issues, thank you.
