### ISSUE TITLE
r130

### ISSUE THREAD

**Issue by joshuaellis** [three-types/three-ts-types#87]
### Issue Tracker

This is used to track potential issues we need to investigate surrounding the `r130` release.

- [x] ~IFCLoader: Geometry optimization, select, hide and property fetch (mrdoob/three.js#21905)~ (#91)
- [x] misc/Volume now has property `this.axisOrder` (mrdoob/three.js#21962)
- [x] ObjectLoader: Add async API (mrdoob/three.js#22031)
- [x] ObjectLoader: Moved json handling to geometries (mrdoob/three.js#22040)
- [x] Add setColors to AxisHelper (mrdoob/three.js#22046)

Last checked: mrdoob/three.js@2383c1c0e4 (5 / 07 / 21).
